version: "3"

services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    env_file: .env
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/import
    ports:
      - 7474:7474
      - 7687:7687
